CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_no CHARACTER VARYING(255) NOT NULL,
    nickname CHARACTER VARYING(255) NOT NULL,
    profile_image_key CHARACTER VARYING(255) NULL,
    is_withdrawn BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE UNIQUE INDEX users_phone_no_active_uk ON users (phone_no) WHERE is_withdrawn = false;

CREATE TABLE IF NOT EXISTS neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code CHARACTER VARYING(255) NOT NULL,
    sido CHARACTER VARYING(255) NOT NULL,
    sigungu CHARACTER VARYING(255) NOT NULL,
    eupmyeondong CHARACTER VARYING(255) NOT NULL,
    boundary GEOMETRY(MULTIPOLYGON, 4326) NULL,
    centroid GEOMETRY(POINT, 4326) NULL,
    CONSTRAINT neighborhoods_pk PRIMARY KEY (id),
    CONSTRAINT neighborhoods_code_uk UNIQUE (code)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS user_neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    neighborhood_id BIGINT NOT NULL,
    location GEOMETRY(POINT, 4326) NOT NULL,
    CONSTRAINT user_neighborhoods_pk PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS rental_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    category CHARACTER VARYING(255) NOT NULL,
    title CHARACTER VARYING(255) NOT NULL,
    description CHARACTER VARYING(255) NOT NULL,
    price_per_day INTEGER NULL,
    price_per_week INTEGER NULL,
    view_count INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT rental_items_pk PRIMARY KEY (id),
    CONSTRAINT rental_items_category_check CHECK (
        (
            (category)::TEXT = ANY (
                (
                    array[
                        'HOUSEHOLD'::CHARACTER VARYING,
                        'TRAVEL'::CHARACTER VARYING,
                        'SPORTS'::CHARACTER VARYING,
                        'ELECTRONIC'::CHARACTER VARYING,
                        'FASHION'::CHARACTER VARYING,
                        'CHILDCARE'::CHARACTER VARYING
                    ]
                )::TEXT[]
            )
        )
    )
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS rental_item_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rental_item_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL,
    key CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT rental_item_images_pk PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS rental_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rental_item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status CHARACTER VARYING(255) NOT NULL,
    rented_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    returned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT rental_records_pk PRIMARY KEY (id),
    CONSTRAINT rental_records_status_check CHECK (
        (
            (status)::TEXT = ANY (
                (
                    array[
                        'RENTED'::CHARACTER VARYING,
                        'RETURNED'::CHARACTER VARYING
                    ]
                )::TEXT[]
            )
        )
    )
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS rental_item_like_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    rental_item_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT rental_item_like_records_pk PRIMARY KEY (id)
) TABLESPACE pg_default;