ALTER TABLE users
ADD COLUMN rent_out_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN rent_in_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
ADD COLUMN neighborhood_verified_at TIMESTAMP WITH TIME ZONE DEFAULT now()