CREATE TABLE IF NOT EXISTS chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rental_item_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chat_rooms_pk PRIMARY KEY (id)
);

CREATE INDEX idx_chat_rooms_rental_item_id
ON chat_rooms (rental_item_id);

CREATE TABLE IF NOT EXISTS chat_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    left_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT chat_participants_pk PRIMARY KEY (id)
);

CREATE INDEX idx_chat_participants_user_id
ON chat_participants (user_id) WHERE left_at IS NULL;

CREATE INDEX idx_chat_participants_chat_room_id
ON chat_participants (chat_room_id) WHERE left_at IS NULL;

CREATE UNIQUE INDEX uk_idx_chat_participants_chat_room_id_user_id
ON chat_participants (chat_room_id, user_id) WHERE left_at IS NULL;