CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chat_messages_pk PRIMARY KEY (id)
);

CREATE INDEX idx_chat_messages_chat_room_id
ON chat_messages (chat_room_id);

CREATE INDEX idx_chat_messages_created_at
ON chat_messages (created_at DESC);